// GENERATED BY BOLT_CLASS_GENERATOR

class BC_Evolve {

   constructor(){
       this.propriety = "";
       this.newValue = null;
       this.speed = "";
       this.time = 0;
 }

}

class BC_Login {

   constructor(){
       this.userName = "exemplePseudo";
       this.hashPass = "exemplepass";
 }

}

class BC_PlayerState {

   constructor(){
       this.life = 1;
       this.lifeMax = 200;
       this.experience = 1;
       this.level = 1;
       this.position = {x : 0,   y : 0,   z : 0};
 }

}


exports.BC_Evolve = BC_Evolve
exports.BC_Login = BC_Login
exports.BC_PlayerState = BC_PlayerState