// GENERATED BY BOLT_CLASS_GENERATOR

class Evolve {

   constructor(){
       this.propriety = "";
       this.newValue = null;
       this.speed = "";
       this.time = 0;
 }

}

class PlayerState {

   constructor(){
       this.life = 1;
       this.lifeMax = 200;
       this.experience = 1;
       this.level = 1;
       this.position = {x : 0,   y : 0,   z : 0};
 }

}


exports.Evolve = Evolve
exports.PlayerState = PlayerState